---

- include_tasks: install.yml
  tags: [pgbouncer, pgbouncer-install]

- include_tasks: configure.yml
  tags: [pgbouncer, pgbouncer-configure]

- include_tasks: monit.yml
  when: monit_protection is defined and monit_protection == true
  tags: [pgbouncer, pgbouncer-monit]

- include_tasks: collectd.yml
  when: collectd_monitoring is defined and collectd_monitoring == true
  tags: [pgbouncer, pgbouncer-collectd]
